sudo: required
dist: trusty

services:
  - postgres

language: ruby

branches:
  only:
    - master

before_script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rake decidim:generate_external_test_app

env:
  - RAILS_ENV=test

cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/.yarn-cache
    - $TRAVIS_BUILD_DIR/node_modules
    - $BUNDLE_PATH
    - vendor/bundle
script:
  - bundle exec rake
  - cd decidim-debates && bundle exec rake

rvm:
  - 2.4.1

notifications:
    email: false

addons:
  postgresql: "9.4"
