# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  valid_auth_url: "<%= ENV['VALID_URL'] %>"
  sentry_enabled: false
  census_url: "<%= ENV['CENSUS_URL'] %>"
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  analytics: <%= ENV["ANALYTICS"].present? %>
  sms:
    service_url: <%= ENV["SMS_SERVICE_URL"] %>
    proxy_url: <%= ENV["SMS_PROXY_URL"] %>
    username: <%= ENV["SMS_USERNAME"] %>
    password: <%= ENV["SMS_PASSWORD"] %>
    service_id: "<%= ENV['SMS_SERVICE_ID'] %>"
    sub_service_id: "<%= ENV['SMS_SUB_SERVICE_ID'] %>"
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: true
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: true
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: true
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  geocoder:
    here_api_key: <%= ENV["HERE_API_KEY"] %>
  timestamp_service_url: "<%= ENV['TIMESTAMP_SERVICE_URL'] %>"
  signature_certificate_password: "<%= ENV['SIGNATURE_CERTIFICATE_PASSWORD'] %>"
  pdf_certificate: <%= ENV["PDF_CERTIFICATE"].to_s.dump %>
  pdf_signer_certificate: <%= ENV["PDF_SIGNER_CERTIFICATE"].to_s.dump %>
  pdf_signer_private_key: <%= ENV["PDF_SIGNER_PRIVATE_KEY"].to_s.dump %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>

development:
  <<: *default
  secret_key_base: e3efe0351af320dda7a3daf90a805a68e94d093cfc57a94bf9c42f3f1732fac32dd4656f435e385f1ea7789ff5e387a6313d1db2a3b11e9dd030293158bfdc9b
  geocoder:
    here_api_key: 1234123412341234
  omniauth:
    developer:
      enabled: true
      icon: phone

test:
  <<: *default
  secret_key_base: 4a6fd36ca5634dbf42f63331b1a236a041976561ec314414d1750f33ef691dd3705ff2828a607d98bee0ba492e11281a33e736c71e959ab04c76679e74ecb564
  geocoder:
    here_api_key: 1234123412341234
  sms:
    service_url: http://example.org/sms
    proxy_url: http://example.org/proxy
    username: username
    password: password
    service_id: "1234"
    sub_service_id: "1234"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  sentry_enabled: true
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email: "<%= ENV["EMAIL"] %>"
  sendgrid: <%= !ENV["SENDGRID_USERNAME"].blank? %>
  smtp_username: <%= ENV["SMTP_USERNAME"] || ENV["SENDGRID_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] || ENV["SENDGRID_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] || "smtp.sendgrid.net" %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] || "heroku.com" %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
